### ISSUE TITLE
Hello and thanks !!!

### ISSUE THREAD

**Issue by reminosouci** [powersj/tilt-shift#1]
Hi thanks for your contribution in the open source. Loving it!!!

just one question very stupid : what is the mask picture ?

I tried your code and get only the blur version in the blur folder. would it be possible to have an exemple?

cheers bro !!!!

**Comment by powersj** [comment]
hi @reminosouci! Thanks for taking the time to open up a bug to ask your question. I have uploaded a directory of example images with their masks and the output. Let me know if that helps you get an idea of what is required. Thanks again!

**Comment by powersj** [comment]
I'm going to go ahead and close this. If you still need additional examples or help please let me know!
